permissions:
  contents: read
name: Test Jekyll site

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.4' # or your desired Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Test HTML output with html-proofer
      run: bundle exec htmlproofer ./_site 
      #run: bundle exec htmlproofer ./_site --disable-external

